import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">ServiceRequestDroneCatFive</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/login">LogIn</Link>
        </li>
        <li>
          <Link to="/registerone">RegisterOne</Link>
        </li>
        <li>
          <Link to="/farmerregisterone">FarmerRegisterOne</Link>
        </li>
        <li>
          <Link to="/farmerregistertwo">FarmerRegisterTwo</Link>
        </li>
        <li>
          <Link to="/mapregisterfarm">MapRegisterFarm</Link>
        </li>
        <li>
          <Link to="/farmerregisterthree">FarmerRegisterThree</Link>
        </li>
        <li>
          <Link to="/mapregisterplotvtwo">MapRegisterPlotvTwo</Link>
        </li>
        <li>
          <Link to="/farmerregisterfour">FarmerRegisterFour</Link>
        </li>
        <li>
          <Link to="/farmerregistereight">FarmerRegisterEight</Link>
        </li>
        <li>
          <Link to="/farmerregisterseven">FarmerRegisterSeven</Link>
        </li>
        <li>
          <Link to="/farmerregisterfive">FarmerRegisterFive</Link>
        </li>
        <li>
          <Link to="/farmerregistersix">FarmerRegisterSix</Link>
        </li>
        <li>
          <Link to="/pilotregisterone">PilotRegisterOne</Link>
        </li>
        <li>
          <Link to="/pilotregistertwo">PilotRegisterTwo</Link>
        </li>
        <li>
          <Link to="/pilotregisterfive">PilotRegisterFive</Link>
        </li>
        <li>
          <Link to="/pilotregisterthree">PilotRegisterThree</Link>
        </li>
        <li>
          <Link to="/pilotregisterfour">PilotRegisterFour</Link>
        </li>
        <li>
          <Link to="/farmerprofile">FarmerProfile</Link>
        </li>
        <li>
          <Link to="/farmprofile">FarmProfile</Link>
        </li>
        <li>
          <Link to="/farmlandprofile">FarmlandProfile</Link>
        </li>
        <li>
          <Link to="/farmverificationprofileone">
            FarmVerificationProfileOne
          </Link>
        </li>
        <li>
          <Link to="/farmverificationprofiletwo">
            FarmVerificationProfileTwo
          </Link>
        </li>
        <li>
          <Link to="/farmverificationprofilethree">
            FarmVerificationProfileThree
          </Link>
        </li>
        <li>
          <Link to="/servicerequestdronecattwo">ServiceRequestDroneCatTwo</Link>
        </li>
        <li>
          <Link to="/farmerdashboard">FarmerDASHBOARD</Link>
        </li>
        <li>
          <Link to="/servicerequestselectfa">ServiceRequestSelectFa</Link>
        </li>
        <li>
          <Link to="/servicerequestdronecatfour">
            ServiceRequestDroneCatFour
          </Link>
        </li>
        <li>
          <Link to="/servicerequestselectedone">ServiceRequestSelectedOne</Link>
        </li>
        <li>
          <Link to="/servicerequestestimatedone">
            ServiceRequestEstimatedOne
          </Link>
        </li>
        <li>
          <Link to="/finishedbookingdatac">FinishedBookingDataC</Link>
        </li>
        <li>
          <Link to="/farmerbookingservicepr">FarmerBookingServicePr</Link>
        </li>
        <li>
          <Link to="/billingdatacollection">BillingDataCollection</Link>
        </li>
        <li>
          <Link to="/servicerequestdronecat">ServiceRequestDroneCat</Link>
        </li>
        <li>
          <Link to="/servicerequestdronecatone">ServiceRequestDroneCatOne</Link>
        </li>
        <li>
          <Link to="/servicerequestselected">ServiceRequestSelected</Link>
        </li>
        <li>
          <Link to="/servicerequestestimated">ServiceRequestEstimated</Link>
        </li>
        <li>
          <Link to="/finishedbookingsurvei">FinishedBookingSurvei</Link>
        </li>
        <li>
          <Link to="/billingsurveillance">BillingSurveillance</Link>
        </li>
        <li>
          <Link to="/servicerequestdronecatthree">
            ServiceRequestDroneCatThree
          </Link>
        </li>
        <li>
          <Link to="/farmerservicereports">FarmerServiceReports</Link>
        </li>
        <li>
          <Link to="/farmerservicereportdetails">
            FarmerServiceReportDetails
          </Link>
        </li>
        <li>
          <Link to="/farmerdashboardmaintenance">
            FarmerDashboardMaintenance
          </Link>
        </li>
        <li>
          <Link to="/farmermaintenancerequest">FarmerMaintenanceRequest</Link>
        </li>
        <li>
          <Link to="/farmermaintenancereques">FarmerMaintenanceReques</Link>
        </li>
        <li>
          <Link to="/maintenancebilling">MaintenanceBilling</Link>
        </li>
        <li>
          <Link to="/maintenanceprocessflow">MaintenanceProcessFlow</Link>
        </li>
        <li>
          <Link to="/draftdronesimulation">DRAFTDroneSimulation</Link>
        </li>
        <li>
          <Link to="/createasimulateddrone">CreateaSimulatedDrone</Link>
        </li>
        <li>
          <Link to="/dronesimulationdetails">DroneSimulationDetails</Link>
        </li>
        <li>
          <Link to="/pilotdashboard">PilotDashboard</Link>
        </li>
        <li>
          <Link to="/pilotschedule">PilotSchedule</Link>
        </li>
        <li>
          <Link to="/pilotscheduletimesperday">PilotScheduleTimesPerDay</Link>
        </li>
        <li>
          <Link to="/adminclouddashboardhome">AdminCloudDashboardHome</Link>
        </li>
        <li>
          <Link to="/adminclouddashboardmap">AdminCloudDashboardMap</Link>
        </li>
        <li>
          <Link to="/adminsimulatedcloudd">AdminSimulatedCloudD</Link>
        </li>
        <li>
          <Link to="/dronefleetstatistics">DroneFleetStatistics</Link>
        </li>
        <li>
          <Link to="/statisticsperservicetype">StatisticsPerServiceType</Link>
        </li>
        <li>
          <Link to="/statisticsdistance">StatisticsDistance</Link>
        </li>
        <li>
          <Link to="/admindashboarddronet">AdminDashboardDroneT</Link>
        </li>
        <li>
          <Link to="/dronetrackingmapdata">DroneTrackingMapData</Link>
        </li>
        <li>
          <Link to="/statisticstime">StatisticsTime</Link>
        </li>
        <li>
          <Link to="/dronearvrtracking">DroneARVRTracking</Link>
        </li>
        <li>
          <Link to="/dronetrackingmapsurv">DroneTrackingMapSurv</Link>
        </li>
        <li>
          <Link to="/draftcloudadminboo">DRAFTCloudAdminBoo</Link>
        </li>
        <li>
          <Link to="/cloudadminsearchstar">CloudAdminSearchStar</Link>
        </li>
        <li>
          <Link to="/initialversiondroneb">INITIALVERSIONDroneB</Link>
        </li>
        <li>
          <Link to="/dronecatalogmissionpone">DroneCatalogMissionPOne</Link>
        </li>
        <li>
          <Link to="/dronecatalogbookings">DroneCatalogBookingS</Link>
        </li>
        <li>
          <Link to="/dronecatalogmissionp">DroneCatalogMissionP</Link>
        </li>
        <li>
          <Link to="/cloudadminsearchscheone">CloudAdminSearchScheOne</Link>
        </li>
        <li>
          <Link to="/cloudadminsearchschetwo">CloudAdminSearchScheTwo</Link>
        </li>
        <li>
          <Link to="/dronemanagement">DroneManagement</Link>
        </li>
        <li>
          <Link to="/adddrone">AddDrone</Link>
        </li>
        <li>
          <Link to="/editdrone">EditDrone</Link>
        </li>
        <li>
          <Link to="/cloudadminsearchschethree">CloudAdminSearchScheThree</Link>
        </li>
        <li>
          <Link to="/cloudadminsearchsche">CloudAdminSearchSche</Link>
        </li>
        <li>
          <Link to="/servicehistory">ServiceHistory</Link>
        </li>
        <li>
          <Link to="/dronedatalivestockda">DroneDataLivestockDa</Link>
        </li>
        <li>
          <Link to="/dronedatalivestock">DroneDataLivestock</Link>
        </li>
        <li>
          <Link to="/dronedata">DroneData</Link>
        </li>
        <li>
          <Link to="/dronedatadataprocessing">DroneDataDataProcessing</Link>
        </li>
        <li>
          <Link to="/dronedatadataanalysis">DroneDataDataAnalysis</Link>
        </li>
        <li>
          <Link to="/droneaiaiservices">DroneAIAIServices</Link>
        </li>
        <li>
          <Link to="/droneaiaimodelmanagement">DroneAIAIModelManagement</Link>
        </li>
        <li>
          <Link to="/droneaimodelevaluations">DroneAIModelEvaluations</Link>
        </li>
        <li>
          <Link to="/systemadminpilotmanaone">SystemAdminPilotManaOne</Link>
        </li>
        <li>
          <Link to="/systemadminpilotmana">SystemAdminPilotMana</Link>
        </li>
        <li>
          <Link to="/servicerequestselectedthree">
            ServiceRequestSelectedThree
          </Link>
        </li>
        <li>
          <Link to="/servicerequestselectedtwo">ServiceRequestSelectedTwo</Link>
        </li>
        <li>
          <Link to="/editselecteddronedetailsone">
            EditSelectedDroneDetailsOne
          </Link>
        </li>
        <li>
          <Link to="/editselecteddronedetailstwo">
            EditSelectedDroneDetailsTwo
          </Link>
        </li>
        <li>
          <Link to="/editselecteddronedetails">EditSelectedDroneDetails</Link>
        </li>
        <li>
          <Link to="/servicerequestselectedfour">
            ServiceRequestSelectedFour
          </Link>
        </li>
        <li>
          <Link to="/signupone">SignUpOne</Link>
        </li>
        <li>
          <Link to="/desktopone">DesktopOne</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
